"""
LN Operator — Database Layer (30%)

SQLite database for tracking everything that happens on your node over time.
This is what makes the tool get smarter — it accumulates historical data that
feeds into the rebalance budget system and the investment advisor.

Tables:
- channel_snapshots: periodic snapshots of every channel's state
- fee_updates: log of every fee policy change made
- rebalance_log: every rebalance attempt (success and failure) with fees paid
- forwarding_log: routing events synced from LND (fees earned per payment forwarded)
- peer_history: actions taken on peers (opened, closed, evaluated)
- investment_log: investment plans generated by the advisor
- graph_snapshots: periodic network-level stats
- alerts: alerts fired (depleted channels, offline peers, etc.)
- channel_maturity: tracks how long each channel has been in a balanced state
  (used by the 3-tier rebalance budget system to judge channel performance)
- sync_state: key-value store for tracking sync cursors (e.g. last LND forwarding
  event offset, so we never fetch the same event twice)
"""

import sqlite3
import json
import time
from contextlib import contextmanager
from config import DB_PATH


def _migrate_rebalance_log():
    """Add payment_hash and triggered_by columns if missing (migration)."""
    with get_conn() as conn:
        cols = [row["name"] for row in conn.execute("PRAGMA table_info(rebalance_log)")]
        if "payment_hash" not in cols:
            conn.execute("ALTER TABLE rebalance_log ADD COLUMN payment_hash TEXT")
        if "triggered_by" not in cols:
            conn.execute("ALTER TABLE rebalance_log ADD COLUMN triggered_by TEXT DEFAULT 'auto'")


def init_db():
    """Create all tables if they don't exist."""
    with get_conn() as conn:
        conn.executescript(SCHEMA)
    _migrate_rebalance_log()


@contextmanager
def get_conn():
    """Context manager for database connections."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


SCHEMA = """
-- ─── Channel snapshots (taken every monitoring run) ─────────────
CREATE TABLE IF NOT EXISTS channel_snapshots (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    ts              INTEGER NOT NULL DEFAULT (strftime('%s','now')),
    chan_id          TEXT NOT NULL,
    peer_pubkey      TEXT NOT NULL,
    peer_alias       TEXT,
    capacity         INTEGER NOT NULL,
    local_balance    INTEGER NOT NULL,
    remote_balance   INTEGER NOT NULL,
    local_ratio      REAL NOT NULL,
    is_active        INTEGER NOT NULL DEFAULT 1,
    fee_rate_ppm     INTEGER,
    base_fee_msat    INTEGER,
    total_sent       INTEGER DEFAULT 0,
    total_received   INTEGER DEFAULT 0,
    num_updates      INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_chan_snap_ts ON channel_snapshots(ts);
CREATE INDEX IF NOT EXISTS idx_chan_snap_chan ON channel_snapshots(chan_id);

-- ─── Fee update log ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS fee_updates (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    ts              INTEGER NOT NULL DEFAULT (strftime('%s','now')),
    chan_id          TEXT NOT NULL,
    peer_alias       TEXT,
    old_fee_ppm      INTEGER,
    new_fee_ppm      INTEGER,
    old_base_msat    INTEGER,
    new_base_msat    INTEGER,
    local_ratio      REAL NOT NULL,
    reason           TEXT
);

-- ─── Rebalance attempts ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS rebalance_log (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    ts              INTEGER NOT NULL DEFAULT (strftime('%s','now')),
    source_chan_id    TEXT NOT NULL,
    target_chan_id    TEXT NOT NULL,
    source_alias     TEXT,
    target_alias     TEXT,
    amount_sats      INTEGER NOT NULL,
    fee_paid_sats    INTEGER,
    fee_ppm          REAL,
    success          INTEGER NOT NULL DEFAULT 0,
    failure_reason   TEXT,
    duration_seconds REAL,
    payment_hash     TEXT,
    triggered_by     TEXT DEFAULT 'auto'
);

-- ─── Forwarding events (routing fees earned) ────────────────────
CREATE TABLE IF NOT EXISTS forwarding_log (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    ts              INTEGER NOT NULL DEFAULT (strftime('%s','now')),
    chan_in          TEXT NOT NULL,
    chan_out         TEXT NOT NULL,
    amount_in_sats   INTEGER NOT NULL,
    amount_out_sats  INTEGER NOT NULL,
    fee_earned_sats  INTEGER NOT NULL
);

-- ─── Sync state (persists last-seen LND index between runs) ─────
CREATE TABLE IF NOT EXISTS sync_state (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- ─── Peer performance tracking ──────────────────────────────────
CREATE TABLE IF NOT EXISTS peer_history (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    ts              INTEGER NOT NULL DEFAULT (strftime('%s','now')),
    pubkey           TEXT NOT NULL,
    alias            TEXT,
    action           TEXT NOT NULL,  -- 'opened', 'closed', 'evaluated', 'rejected'
    channel_size     INTEGER,
    reason           TEXT,
    performance_notes TEXT
);

-- ─── Investment decisions ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS investment_log (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    ts              INTEGER NOT NULL DEFAULT (strftime('%s','now')),
    total_sats       INTEGER NOT NULL,
    treasury_reserve INTEGER NOT NULL,
    deployable_sats  INTEGER NOT NULL,
    plan_json        TEXT NOT NULL,      -- full recommendation as JSON
    agent_summary    TEXT,               -- Claude's plain-English summary
    executed         INTEGER DEFAULT 0,  -- did the user follow through?
    outcome_notes    TEXT                -- post-hoc notes on how it went
);

-- ─── Network graph snapshots (periodic) ─────────────────────────
CREATE TABLE IF NOT EXISTS graph_snapshots (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    ts              INTEGER NOT NULL DEFAULT (strftime('%s','now')),
    total_nodes      INTEGER,
    total_channels   INTEGER,
    total_capacity   INTEGER,
    our_channels     INTEGER,
    our_capacity     INTEGER,
    our_peers        INTEGER
);

-- ─── Alerts sent ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS alerts (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    ts              INTEGER NOT NULL DEFAULT (strftime('%s','now')),
    alert_type       TEXT NOT NULL,      -- 'channel_depleted', 'peer_offline', 'rebalance_failed', etc.
    channel_id       TEXT,
    message          TEXT NOT NULL,
    sent_telegram    INTEGER DEFAULT 0
);

-- ─── Channel maturity tracking ──────────────────────────────────
-- Tracks how much time each channel has spent in a balanced state,
-- so the rebalance budget can distinguish "unproven" from "proven unprofitable".
CREATE TABLE IF NOT EXISTS channel_maturity (
    chan_id          TEXT PRIMARY KEY,
    first_seen       INTEGER NOT NULL DEFAULT (strftime('%s','now')),
    balanced_seconds INTEGER NOT NULL DEFAULT 0,  -- cumulative time spent balanced
    last_snapshot_ts INTEGER NOT NULL DEFAULT 0,   -- when we last checked
    last_was_balanced INTEGER NOT NULL DEFAULT 0   -- was it balanced at last check?
);

-- ─── Channel backup attempts (off-site channel.backup rsync) ────
CREATE TABLE IF NOT EXISTS backup_log (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    ts           INTEGER NOT NULL DEFAULT (strftime('%s','now')),
    success      INTEGER NOT NULL,
    file_mtime   INTEGER,           -- mtime of channel.backup when uploaded
    file_bytes   INTEGER,           -- size of the file uploaded
    destination  TEXT,              -- e.g. user@host:/path/
    duration_ms  INTEGER,
    trigger      TEXT,              -- 'path', 'timer', 'manual'
    error        TEXT
);
CREATE INDEX IF NOT EXISTS idx_backup_log_ts ON backup_log(ts);

-- ─── Manual fee overrides ───────────────────────────────────────
-- Pins a channel's outbound fee_rate_ppm so the auto-fee pipeline
-- leaves it alone. Removed when the operator runs `clear_fee`.
CREATE TABLE IF NOT EXISTS fee_overrides (
    chan_id      TEXT PRIMARY KEY,
    pinned_ppm   INTEGER NOT NULL,
    set_at       INTEGER NOT NULL DEFAULT (strftime('%s','now')),
    note         TEXT
);

-- ─── Per-channel slow-moving signals ────────────────────────────
-- Populated by `main.py recompute_signals` (nightly).
--   market_multiplier    : nudge applied to sigmoid base (e.g. +0.2 → 120%)
--   last_fee_update_ts   : when this channel was last broadcast (hysteresis)
--   last_local_ratio     : for edge-zone-crossing detection
-- Vestigial columns (kept to avoid migration; no longer written or read by
-- engine.py — rebalance budget and fee floor are derived live from rebalance_log):
--   rebalance_cost_floor_*  : superseded by last_refill_ppm × REBALANCE_FEE_MARGIN
--   adaptive_cap_*          : superseded by last_refill_ppm + failure escalation
CREATE TABLE IF NOT EXISTS channel_signals (
    chan_id                       TEXT PRIMARY KEY,
    market_multiplier             REAL    NOT NULL DEFAULT 0.0,
    rebalance_cost_floor_ppm      INTEGER NOT NULL DEFAULT 0,  -- vestigial
    rebalance_cost_floor_samples  INTEGER NOT NULL DEFAULT 0,  -- vestigial
    rebalance_cost_floor_source   TEXT,                         -- vestigial
    adaptive_cap_ppm              INTEGER NOT NULL DEFAULT 0,   -- vestigial
    adaptive_cap_samples          INTEGER NOT NULL DEFAULT 0,   -- vestigial
    last_fee_update_ts            INTEGER NOT NULL DEFAULT 0,
    last_local_ratio              REAL,
    signals_updated_ts            INTEGER NOT NULL DEFAULT 0
);
"""


# ─── Helper functions ────────────────────────────────────────────

def save_channel_snapshot(channels: list[dict]):
    """Save a snapshot of all channels."""
    with get_conn() as conn:
        for ch in channels:
            conn.execute("""
                INSERT INTO channel_snapshots
                (chan_id, peer_pubkey, peer_alias, capacity, local_balance,
                 remote_balance, local_ratio, is_active, fee_rate_ppm,
                 base_fee_msat, total_sent, total_received, num_updates)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                ch["chan_id"], ch["peer_pubkey"], ch.get("peer_alias", ""),
                ch["capacity"], ch["local_balance"], ch["remote_balance"],
                ch["local_ratio"], int(ch.get("active", True)),
                ch.get("fee_rate_ppm"), ch.get("base_fee_msat"),
                ch.get("total_sent", 0), ch.get("total_received", 0),
                ch.get("num_updates", 0)
            ))


def save_fee_update(chan_id, peer_alias, old_ppm, new_ppm, old_base, new_base,
                    local_ratio, reason=""):
    """Log a fee policy change."""
    with get_conn() as conn:
        conn.execute("""
            INSERT INTO fee_updates
            (chan_id, peer_alias, old_fee_ppm, new_fee_ppm, old_base_msat,
             new_base_msat, local_ratio, reason)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """, (chan_id, peer_alias, old_ppm, new_ppm, old_base, new_base,
              local_ratio, reason))


def save_rebalance_attempt(source_chan, target_chan, source_alias, target_alias,
                           amount, fee_paid, success, failure_reason="",
                           duration=0.0, payment_hash=None):
    """Log a rebalance attempt."""
    fee_ppm = (fee_paid / amount * 1_000_000) if amount > 0 and fee_paid else 0
    with get_conn() as conn:
        conn.execute("""
            INSERT INTO rebalance_log
            (source_chan_id, target_chan_id, source_alias, target_alias,
             amount_sats, fee_paid_sats, fee_ppm, success, failure_reason,
             duration_seconds, payment_hash, triggered_by)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'auto')
        """, (source_chan, target_chan, source_alias, target_alias,
              amount, fee_paid, fee_ppm, int(success), failure_reason, duration,
              payment_hash))


def save_forwarding_events(events: list[dict]):
    """Log forwarding events from LND."""
    with get_conn() as conn:
        for ev in events:
            conn.execute("""
                INSERT INTO forwarding_log
                (ts, chan_in, chan_out, amount_in_sats, amount_out_sats, fee_earned_sats)
                VALUES (?, ?, ?, ?, ?, ?)
            """, (
                ev.get("timestamp", int(time.time())),
                ev["chan_in"], ev["chan_out"],
                ev["amount_in"], ev["amount_out"], ev["fee_earned"]
            ))


def save_investment_plan(total_sats, treasury, deployable, plan_dict, agent_summary=""):
    """Log an investment recommendation."""
    with get_conn() as conn:
        conn.execute("""
            INSERT INTO investment_log
            (total_sats, treasury_reserve, deployable_sats, plan_json, agent_summary)
            VALUES (?, ?, ?, ?, ?)
        """, (total_sats, treasury, deployable, json.dumps(plan_dict), agent_summary))


def set_fee_override(chan_id, ppm, note=""):
    """Pin a channel's outbound fee rate. Overwrites any existing pin."""
    with get_conn() as conn:
        conn.execute("""
            INSERT INTO fee_overrides (chan_id, pinned_ppm, set_at, note)
            VALUES (?, ?, strftime('%s','now'), ?)
            ON CONFLICT(chan_id) DO UPDATE SET
              pinned_ppm = excluded.pinned_ppm,
              set_at     = excluded.set_at,
              note       = excluded.note
        """, (chan_id, int(ppm), note or None))


def clear_fee_override(chan_id):
    """Remove a fee pin. Returns True if a pin existed, False otherwise."""
    with get_conn() as conn:
        cur = conn.execute("DELETE FROM fee_overrides WHERE chan_id = ?", (chan_id,))
        return cur.rowcount > 0


def get_fee_overrides():
    """Return all fee pins as {chan_id: {pinned_ppm, set_at, note}}."""
    with get_conn() as conn:
        rows = conn.execute(
            "SELECT chan_id, pinned_ppm, set_at, note FROM fee_overrides"
        ).fetchall()
        return {
            r["chan_id"]: {
                "pinned_ppm": r["pinned_ppm"],
                "set_at": r["set_at"],
                "note": r["note"],
            }
            for r in rows
        }


def save_alert(alert_type, message, channel_id=None, sent_telegram=False):
    """Log an alert."""
    with get_conn() as conn:
        conn.execute("""
            INSERT INTO alerts (alert_type, channel_id, message, sent_telegram)
            VALUES (?, ?, ?, ?)
        """, (alert_type, channel_id, message, int(sent_telegram)))


# ─── Query helpers ───────────────────────────────────────────────

def get_avg_monthly_rebalance_cost(months=3):
    """Average monthly rebalancing cost over the last N months."""
    cutoff = int(time.time()) - (months * 30 * 86400)
    with get_conn() as conn:
        row = conn.execute("""
            SELECT COALESCE(SUM(fee_paid_sats), 0) as total_fees,
                   COUNT(*) as attempts
            FROM rebalance_log
            WHERE ts > ? AND success = 1
        """, (cutoff,)).fetchone()
        total = row["total_fees"]
        return total / months if months > 0 else 0


def get_avg_monthly_fee_revenue(months=3):
    """Average monthly routing fee revenue over the last N months."""
    cutoff = int(time.time()) - (months * 30 * 86400)
    with get_conn() as conn:
        row = conn.execute("""
            SELECT COALESCE(SUM(fee_earned_sats), 0) as total_fees
            FROM forwarding_log
            WHERE ts > ?
        """, (cutoff,)).fetchone()
        return row["total_fees"] / months if months > 0 else 0


def get_channel_fee_revenue(chan_id, days=30):
    """Fee revenue for a specific channel over last N days."""
    cutoff = int(time.time()) - (days * 86400)
    with get_conn() as conn:
        row = conn.execute("""
            SELECT COALESCE(SUM(fee_earned_sats), 0) as fees
            FROM forwarding_log
            WHERE (chan_in = ? OR chan_out = ?) AND ts > ?
        """, (chan_id, chan_id, cutoff)).fetchone()
        return row["fees"]


def get_peer_history(pubkey):
    """Get all historical actions for a peer."""
    with get_conn() as conn:
        return conn.execute("""
            SELECT * FROM peer_history WHERE pubkey = ? ORDER BY ts DESC
        """, (pubkey,)).fetchall()


def get_recent_rebalance_stats(days=30):
    """Rebalancing stats for the last N days."""
    cutoff = int(time.time()) - (days * 86400)
    with get_conn() as conn:
        return conn.execute("""
            SELECT COUNT(*) as total_attempts,
                   SUM(success) as successes,
                   COALESCE(SUM(CASE WHEN success=1 THEN fee_paid_sats END), 0) as total_fees,
                   COALESCE(AVG(CASE WHEN success=1 THEN fee_ppm END), 0) as avg_fee_ppm,
                   COALESCE(SUM(CASE WHEN success=1 THEN amount_sats END), 0) as total_rebalanced
            FROM rebalance_log WHERE ts > ?
        """, (cutoff,)).fetchone()


def get_channel_performance(chan_id, days=30):
    """Get performance summary for a channel."""
    cutoff = int(time.time()) - (days * 86400)
    with get_conn() as conn:
        # Fee revenue
        revenue = conn.execute("""
            SELECT COALESCE(SUM(fee_earned_sats), 0) as fees,
                   COUNT(*) as forwards
            FROM forwarding_log
            WHERE (chan_in = ? OR chan_out = ?) AND ts > ?
        """, (chan_id, chan_id, cutoff)).fetchone()

        # Rebalancing costs
        rebal = conn.execute("""
            SELECT COALESCE(SUM(fee_paid_sats), 0) as costs,
                   COUNT(*) as attempts,
                   SUM(success) as successes
            FROM rebalance_log
            WHERE (source_chan_id = ? OR target_chan_id = ?) AND ts > ?
        """, (chan_id, chan_id, cutoff)).fetchone()

        return {
            "fee_revenue": revenue["fees"],
            "forwards": revenue["forwards"],
            "rebalance_cost": rebal["costs"],
            "rebalance_attempts": rebal["attempts"],
            "rebalance_successes": rebal["successes"] or 0,
            "net_profit": revenue["fees"] - rebal["costs"],
        }


# ─── Channel maturity tracking ──────────────────────────────────

def update_channel_maturity(chan_id, is_balanced_now):
    """Update the balanced-time accumulator for a channel.

    Called every monitoring run. If the channel was balanced at the last
    snapshot AND is still balanced now, we add the elapsed time to
    balanced_seconds.
    """
    now = int(time.time())
    with get_conn() as conn:
        row = conn.execute(
            "SELECT * FROM channel_maturity WHERE chan_id = ?", (chan_id,)
        ).fetchone()

        if row is None:
            # First time seeing this channel
            conn.execute("""
                INSERT INTO channel_maturity
                (chan_id, first_seen, balanced_seconds, last_snapshot_ts, last_was_balanced)
                VALUES (?, ?, 0, ?, ?)
            """, (chan_id, now, now, int(is_balanced_now)))
            return

        elapsed = now - row["last_snapshot_ts"]
        # Only accumulate if it was balanced at BOTH the last check and now
        add_seconds = elapsed if (row["last_was_balanced"] and is_balanced_now) else 0

        conn.execute("""
            UPDATE channel_maturity
            SET balanced_seconds = balanced_seconds + ?,
                last_snapshot_ts = ?,
                last_was_balanced = ?
            WHERE chan_id = ?
        """, (add_seconds, now, int(is_balanced_now), chan_id))


def get_channel_maturity(chan_id):
    """Get maturity info for a channel.

    Returns dict with:
    - balanced_days: total days spent in a balanced state
    - age_days: total days since first seen
    - balanced_ratio: fraction of lifetime spent balanced
    """
    with get_conn() as conn:
        row = conn.execute(
            "SELECT * FROM channel_maturity WHERE chan_id = ?", (chan_id,)
        ).fetchone()

    if row is None:
        return {"balanced_days": 0, "age_days": 0, "balanced_ratio": 0}

    now = int(time.time())
    age_seconds = max(1, now - row["first_seen"])
    return {
        "balanced_days": row["balanced_seconds"] / 86400,
        "age_days": age_seconds / 86400,
        "balanced_ratio": row["balanced_seconds"] / age_seconds,
    }


def get_channel_earned_ppm(chan_id, days=30):
    """Calculate the average ppm this channel has earned over the last N days.

    Looks at forwarding events where this channel was involved (in or out)
    and computes: total_fees / total_amount_routed * 1_000_000
    """
    cutoff = int(time.time()) - (days * 86400)
    with get_conn() as conn:
        row = conn.execute("""
            SELECT COALESCE(SUM(fee_earned_sats), 0) as total_fees,
                   COALESCE(SUM(amount_out_sats), 0) as total_routed
            FROM forwarding_log
            WHERE (chan_in = ? OR chan_out = ?) AND ts > ?
        """, (chan_id, chan_id, cutoff)).fetchone()

    if row["total_routed"] == 0:
        return 0.0
    return row["total_fees"] / row["total_routed"] * 1_000_000


def rebalance_exists_by_hash(payment_hash):
    """Check if a rebalance with this payment hash is already in the log."""
    with get_conn() as conn:
        row = conn.execute(
            "SELECT id FROM rebalance_log WHERE payment_hash = ?",
            (payment_hash,)
        ).fetchone()
        return row is not None


def save_manual_rebalance(source_chan_id, target_chan_id, source_alias, target_alias,
                          amount_sats, fee_paid_sats, payment_hash, ts):
    """Save a manually-executed rebalance discovered from LND payments."""
    with get_conn() as conn:
        fee_ppm = fee_paid_sats / amount_sats * 1_000_000 if amount_sats > 0 else 0
        conn.execute("""
            INSERT INTO rebalance_log
            (ts, source_chan_id, target_chan_id, source_alias, target_alias,
             amount_sats, fee_paid_sats, fee_ppm, success, failure_reason,
             duration_seconds, payment_hash, triggered_by)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1, NULL, NULL, ?, 'manual')
        """, (ts, source_chan_id, target_chan_id, source_alias, target_alias,
              amount_sats, fee_paid_sats, fee_ppm, payment_hash))


def get_repeated_rebalance_failures(chan_id, min_failures=3):
    """Check if a channel has failed to rebalance N+ times in a row.

    Returns the count of consecutive failures if >= min_failures, else 0.
    Looks at the most recent N rebalance attempts for this channel
    and checks if they are all failures.
    """
    with get_conn() as conn:
        rows = conn.execute("""
            SELECT success FROM rebalance_log
            WHERE (source_chan_id = ? OR target_chan_id = ?)
            ORDER BY ts DESC LIMIT ?
        """, (chan_id, chan_id, min_failures)).fetchall()

    if len(rows) < min_failures:
        return 0  # not enough history yet

    # Check if all recent attempts failed
    if all(not row["success"] for row in rows):
        return len(rows)
    return 0


def save_backup_attempt(success, file_mtime, file_bytes, destination,
                        duration_ms, trigger, error=None):
    """Log a channel.backup upload attempt."""
    with get_conn() as conn:
        conn.execute("""
            INSERT INTO backup_log
            (success, file_mtime, file_bytes, destination, duration_ms, trigger, error)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        """, (int(bool(success)), file_mtime, file_bytes, destination,
              duration_ms, trigger, error))


def get_latest_backup_status():
    """Return last attempt row and last successful row (both may be None).

    The dashboard uses this to render age + last error.
    """
    with get_conn() as conn:
        last_any = conn.execute(
            "SELECT * FROM backup_log ORDER BY ts DESC LIMIT 1"
        ).fetchone()
        last_ok = conn.execute(
            "SELECT * FROM backup_log WHERE success=1 ORDER BY ts DESC LIMIT 1"
        ).fetchone()
    return {
        "last_attempt": dict(last_any) if last_any else None,
        "last_success": dict(last_ok) if last_ok else None,
    }


# ─── Channel signals (slow-moving per-channel state) ───────────

def get_channel_signals(chan_id):
    """Return the channel_signals row for a channel, or a defaults dict."""
    with get_conn() as conn:
        row = conn.execute(
            "SELECT * FROM channel_signals WHERE chan_id = ?", (chan_id,)
        ).fetchone()
    if row is None:
        return {
            "chan_id": chan_id,
            "market_multiplier": 0.0,
            "rebalance_cost_floor_ppm": 0,
            "rebalance_cost_floor_samples": 0,
            "rebalance_cost_floor_source": None,
            "adaptive_cap_ppm": 0,
            "adaptive_cap_samples": 0,
            "last_fee_update_ts": 0,
            "last_local_ratio": None,
            "signals_updated_ts": 0,
        }
    return dict(row)


def upsert_channel_signals(chan_id, **fields):
    """Insert or update a channel_signals row. Only writes provided fields."""
    if not fields:
        return
    cols = list(fields.keys())
    placeholders = ", ".join(f"{c} = excluded.{c}" for c in cols)
    col_list = ", ".join(["chan_id"] + cols)
    val_list = ", ".join(["?"] * (len(cols) + 1))
    params = [chan_id] + [fields[c] for c in cols]
    with get_conn() as conn:
        conn.execute(
            f"INSERT INTO channel_signals ({col_list}) VALUES ({val_list}) "
            f"ON CONFLICT(chan_id) DO UPDATE SET {placeholders}",
            params,
        )


def get_target_rebalance_ppms(chan_id, days=30, auto_only=False):
    """Return list of successful fee_ppm values for rebalances INTO this channel.

    Used to compute the rebalance-cost floor and the adaptive cap.
    """
    cutoff = int(time.time()) - days * 86400
    sql = """
        SELECT fee_ppm FROM rebalance_log
        WHERE target_chan_id = ? AND ts > ? AND success = 1
          AND fee_ppm IS NOT NULL
    """
    params = [chan_id, cutoff]
    if auto_only:
        sql += " AND triggered_by = 'auto'"
    with get_conn() as conn:
        return [r["fee_ppm"] for r in conn.execute(sql, params).fetchall()]


def get_last_forward_ts(chan_id):
    """Most recent forwarding event ts where this channel was in or out, or None."""
    with get_conn() as conn:
        row = conn.execute(
            "SELECT MAX(ts) AS ts FROM forwarding_log WHERE chan_in = ? OR chan_out = ?",
            (chan_id, chan_id),
        ).fetchone()
    return row["ts"] if row and row["ts"] else None


def get_last_refill_ppm(chan_id):
    """Return the fee_ppm of the most recent SUCCESSFUL rebalance into this channel.

    Drives both the rebalance budget and the outbound fee floor.
    Returns None if the channel has never been successfully refilled.
    """
    with get_conn() as conn:
        row = conn.execute("""
            SELECT fee_ppm FROM rebalance_log
            WHERE target_chan_id = ? AND success = 1 AND fee_ppm IS NOT NULL
            ORDER BY ts DESC LIMIT 1
        """, (chan_id,)).fetchone()
    return int(row["fee_ppm"]) if row else None


def count_failures_since_last_success(chan_id):
    """Count failed rebalance attempts into this channel since its last success.

    Returns 0 if no history or the last attempt was a success. Used to
    escalate the rebalance budget on persistent failure (bootstrap and
    upward-drift recovery).
    """
    with get_conn() as conn:
        last_ok = conn.execute("""
            SELECT MAX(ts) AS ts FROM rebalance_log
            WHERE target_chan_id = ? AND success = 1
        """, (chan_id,)).fetchone()
        cutoff = last_ok["ts"] if last_ok and last_ok["ts"] else 0
        row = conn.execute("""
            SELECT COUNT(*) AS n FROM rebalance_log
            WHERE target_chan_id = ? AND success = 0 AND ts > ?
        """, (chan_id, cutoff)).fetchone()
    return int(row["n"]) if row else 0


def get_sync_state(key, default=None):
    """Get a value from sync_state table."""
    with get_conn() as conn:
        row = conn.execute(
            "SELECT value FROM sync_state WHERE key=?", (key,)
        ).fetchone()
        return row["value"] if row else default


def set_sync_state(key, value):
    """Set a value in sync_state table."""
    with get_conn() as conn:
        conn.execute(
            "INSERT OR REPLACE INTO sync_state (key, value) VALUES (?, ?)",
            (key, str(value))
        )


if __name__ == "__main__":
    init_db()
    print(f"Database initialised at {DB_PATH}")
else:
    # Run migration on import to add new columns if missing
    try:
        _migrate_rebalance_log()
    except Exception:
        pass  # DB may not exist yet
